version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "zod"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "zod"
        versions:
          - ">=3.25.68 <4"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
